-- Creación de tablas
CREATE TABLE roles (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE "users_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users_id" integer NOT NULL,
  "categories_id" integer NOT NULL
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  age INTEGER,
  role_id INTEGER NOT NULL,
  CONSTRAINT fk_users_roles FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE courses (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  level VARCHAR(20),
  teacher VARCHAR(100),
  category_id INTEGER NOT NULL,
  CONSTRAINT fk_courses_categories FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE course_videos (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  url VARCHAR(200) NOT NULL,
  course_id INTEGER NOT NULL,
  CONSTRAINT fk_course_videos_courses FOREIGN KEY (course_id) REFERENCES courses(id)
);

-- Inserción de datos de ejemplo
INSERT INTO roles (name) VALUES ('student');
INSERT INTO roles (name) VALUES ('teacher');
INSERT INTO roles (name) VALUES ('admin');

INSERT INTO categories (name) VALUES ('Programación');
INSERT INTO categories (name) VALUES ('Diseño');
INSERT INTO categories (name) VALUES ('Marketing');

INSERT INTO users (name, email, password, age, role_id) VALUES ('Juan Perez', 'juan@example.com', 'contraseña', 30, 2);
INSERT INTO users (name, email, password, age, role_id) VALUES ('Maria Gomez', 'maria@example.com', 'contraseña', 25, 1);

INSERT INTO courses (title, description, level, teacher, category_id) VALUES ('Curso de HTML', 'Aprende HTML desde cero', 'Principiante', 'Ana Rodriguez', 1);
INSERT INTO courses (title, description, level, teacher, category_id) VALUES ('Curso de Photoshop', 'Aprende a diseñar con Photoshop', 'Intermedio', 'Carlos Gutierrez', 2);

INSERT INTO course_videos (title, url, course_id) VALUES ('Introducción a HTML', 'https://www.youtube.com/watch?v=_93kDSPlKIM', 2);
INSERT INTO course_videos (title, url, course_id) VALUES ('Herramientas de selección en Photoshop', 'https://www.youtube.com/watch?v=cOtVwaMMpR8', 2);
